[wip] docs: more details about built oo indices
openshift/ci-tools pull request #1247
Opened 2020-09-22 12:36 UTC by petr-muller

Be more informational about how the indices are built.

WIP: I'd like to add a link to the docs that describe `opm index add` modes but I need to find one.

2020-09-22 20:59 UTC, stevekuznetsov requested changes

2020-09-22 20:59 UTC, stevekuznetsov commented on pkg/webreg/webreg.go
> +Thi ephemeral index is built from scratch and only the bundles built in the
`s/Thi/This/`

2020-09-22 20:59 UTC, stevekuznetsov commented on pkg/webreg/webreg.go
> +that the CSV version needs to be a valid semver. Also, if the CSV has a <code>spec.replaces</code>
nit: CSV stands for Cluster Service Version so "CSV Version" is like PIN Number. Maybe specifically call out `csv.spec.version`?

2020-09-23 06:24 UTC, mgencur commented on pkg/webreg/webreg.go
> +replaced version.
@petr-muller thanks for adding these details! I'll need to try it soon:)

2020-09-23 11:44 UTC, petr-muller commented
Thanks, addressed!

2020-09-24 01:38 UTC, stevekuznetsov commented
/lgtm

2020-09-24 03:16 UTC, merged