pull the entrypoint-wrapper image from the local registry instead
openshift/ci-tools pull request #2937
Opened 2022-08-08 17:14 UTC by droslean

/cc @bbguimaraes @openshift/test-platform 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

2022-08-09 16:14 UTC, bbguimaraes requested changes
I fear this will become a continuous hunt for cases where the namespace should/shouldn't be altered, with the conflation of `ImageStreamTagReference` for internal and external images and the "stringly-typed" namespace fields.  What about `base_rpm_images`, `tag_specification`, `releases`, `build_root`, …?

To do this safely, we should IMO:

- derive a type from `ImageStreamTagReference` (possibly a corresponding one for `namespace` fields, as in e.g. `PromotionConfiguration`) for tags which need this special treatment
- go through the entirety of `pkg/api` / https://steps.ci.openshift.org/ci-operator-reference and change external references to use those types (`BaseImages`, `BaseRPMImages`, etc.)
- add the `NamespaceWithArch` method to _those types only_

We will also need tests.

2022-08-09 17:38 UTC, droslean commented on pkg/util/util.go
> +	arch := runtime.GOARCH
The only way to test it is to run the tests in `arm01` cluster.

2022-08-10 13:59 UTC, droslean commented on pkg/api/types.go
> +
You can't even imagine what happens to the code if we introduce a new struct for this case.... :)

2022-08-10 14:02 UTC, droslean commented
@bbguimaraes Yea we should do this one by one. I will introduce a new type for the multi-arch cases. In this PR I will try to change only `base_images` and `base_rpm_images` if it won't affect anything else...

2022-08-16 17:55 UTC, droslean commented
@bbguimaraes The latest changes in this PR, allow all input images to resolve their namespace based on the architecture. I believe that this is a good way to start. I will follow up by adding this feature for the rest of the hardcoded images we are using like `clonerefs`

2022-08-17 11:56 UTC, bbguimaraes commented
/lgtm

2022-08-17 13:00 UTC, droslean commented
/test e2e

2022-08-17 14:43 UTC, merged