Add test config minimum_interval
openshift/ci-tools pull request #2980
Opened 2022-08-29 14:15 UTC by pierreprinetti

Based on: https://github.com/kubernetes/test-infra/pull/26743

2022-08-29 16:51 UTC, smg247 commented on cmd/release-job-migrator/main.go
> +				interval = &minimumIntervalCopy
you want to set `minimumInterval` here instead

2022-08-30 07:42 UTC, pierreprinetti commented
This will have to wait for https://github.com/kubernetes/test-infra/pull/27304
/hold

2022-09-02 14:32 UTC, pierreprinetti commented
`UPDATE=true make test` still geenrates `minimun_interval` with a typo. Perhaps next week?

2022-09-07 08:51 UTC, pierreprinetti commented
/hold cancel
Now the problem seems to be that 

>  The ci-chat-bot repo vendors test-infra at e655beaa3871, which is older than the ci-tools vendor at 0e2e39caed68

Looks like I'll have to wait for a bump in ci-chat-bot?

2022-09-07 11:20 UTC, smg247 commented
> > The ci-chat-bot repo vendors test-infra at [e655bea](https://github.com/openshift/ci-tools/commit/e655beaa387138967f72065b33e6dc264accf712), which is older than the ci-tools vendor at 0e2e39caed68
> 
> Looks like I'll have to wait for a bump in ci-chat-bot?

Yes, `ci-chat-bot` and `release-controller` cannot have an older version of `test-infra` than `ci-tools`. You will have to bump both of them to the same version.

2022-09-07 14:24 UTC, pierreprinetti commented
/retest

2022-09-07 14:48 UTC, smg247 requested changes
You'll also need to add a validation like we have for: https://github.com/openshift/ci-tools/blob/7837783c02f4e86594f6048f3c28614816f96472/pkg/validation/test.go#L163-L165 to verify that this field isn't set with `cron` or `interval`

2022-09-08 08:24 UTC, pierreprinetti commented on pkg/steps/release/promote.go
> +	if refs := s.jobSpec.Refs; refs != nil {
`MainRefs()` [is not an exported method any more](https://github.com/kubernetes/test-infra/commit/51b20129359466d7c7ce3bb8457b7a648b29ecfa#diff-3062bdb94a540e9fb07c50039ad8b2190ecb3c2e38cf190b03dfc81afcff781fR196).

2022-09-08 09:06 UTC, pierreprinetti commented
@smg247 Validation added, thanks! PTAL

2022-09-09 07:46 UTC, pierreprinetti commented on pkg/steps/release/promote.go
> +	if refs := s.jobSpec.Refs; refs != nil {
Done!

2022-09-09 12:50 UTC, smg247 commented
/lgtm

2022-09-09 15:48 UTC, merged