cluster-init: add flag use-token-file-in-kubeconfig
openshift/ci-tools pull request #3036
Opened 2022-09-23 21:08 UTC by hongkailiu

/cc @smg247

2022-09-26 15:04 UTC, hongkailiu commented
/test breaking-changes

2022-10-04 18:28 UTC, smg247 requested changes

2022-10-04 19:56 UTC, hongkailiu commented on cmd/cluster-init/update_bootstrap_secrets.go
> +		if err := updateSecretItemContext(c, "pj-rehearse", string(api.ClusterBuild01), keyAndFieldToken, secretbootstrap.ItemContext{
Done!

2022-10-04 19:56 UTC, hongkailiu commented on cmd/cluster-init/update_bootstrap_secrets.go
> +			fmt.Sprintf("sa.pod-scaler.%s.%s", o.clusterName, token), secretbootstrap.ItemContext{
Updated.

2022-10-04 20:00 UTC, hongkailiu commented
/hold

2022-10-20 15:20 UTC, hongkailiu commented
/test breaking-changes

2022-10-20 15:58 UTC, smg247 commented
/lgtm

2022-10-20 17:36 UTC, hongkailiu commented
/hold cancel

2022-10-20 21:58 UTC, merged