Repo Brancher tool: better errors handling
openshift/ci-tools pull request #3051
Opened 2022-09-28 12:54 UTC by danilo-gemoli

Repo Brancher tool seems to report false positive errors (see [here](https://storage.googleapis.com/origin-ci-test/logs/periodic-openshift-release-fast-forward/1574997720924426240/build-log.txt)) even when everything went well.

### Description:
False positives manifest themselves when the following execution path takes place:
1. the tool initializes and fetches a repository
2. an attempt to forward the `futureRelease` tag is made
  2.1. ~~if it went wrong then the error is recorded and the tool is going to fetch deeper and retry~~ **My bad, that's not true**
  2.2. otherwise keep going with the remaing work
 
An error that rose in the middle of a retry (step 2.1.) is treated as a general failure of the entire execution.

2022-09-29 08:28 UTC, droslean approved these changes

2022-09-29 08:35 UTC, droslean commented
/hold

2022-09-30 10:35 UTC, bbguimaraes requested changes
We could make the output a bit better, but it's not a false positive; there were actual errors in the execution:

```
time="2022-09-28T05:52:34Z" level=error msg="Failed to execute command." branch=master commands="git push https://openshift-merge-robot:xxx@github.com/openshift/openshift-tests FETCH_HEAD:refs/heads/release-4.13" future-branch=release-4.13 org=openshift output="remote: This repository was archived so it is read-only.\nfatal: unable to access 'https://github.com/openshift/openshift-tests/': The requested URL returned error: 403\n" repo=openshift-tests source-file=openshift-openshift-tests-master.yaml variant=
time="2022-09-28T05:52:41Z" level=error msg="Failed to execute command." branch=master commands="git push https://openshift-merge-robot:xxx@github.com/openshift/openshift-tests FETCH_HEAD:refs/heads/release-4.12" future-branch=release-4.12 org=openshift output="remote: This repository was archived so it is read-only.\nfatal: unable to access 'https://github.com/openshift/openshift-tests/': The requested URL returned error: 403\n" repo=openshift-tests source-file=openshift-openshift-tests-master.yaml variant=
```

The `error="<nil>"` at the end is due to the condition:

https://github.com/openshift/ci-tools/blob/68249882ebce83a5f9b093b313adad88d67f67dd/cmd/repo-brancher/main.go#L203

which I suppose is constructed that way to process as many repositories as possible before failing.

2022-10-07 14:28 UTC, bear-redhat commented
> We could make the output a bit better, but it's not a false positive; there were actual errors in the execution:
> 
> ```
> time="2022-09-28T05:52:34Z" level=error msg="Failed to execute command." branch=master commands="git push https://openshift-merge-robot:xxx@github.com/openshift/openshift-tests FETCH_HEAD:refs/heads/release-4.13" future-branch=release-4.13 org=openshift output="remote: This repository was archived so it is read-only.\nfatal: unable to access 'https://github.com/openshift/openshift-tests/': The requested URL returned error: 403\n" repo=openshift-tests source-file=openshift-openshift-tests-master.yaml variant=
> time="2022-09-28T05:52:41Z" level=error msg="Failed to execute command." branch=master commands="git push https://openshift-merge-robot:xxx@github.com/openshift/openshift-tests FETCH_HEAD:refs/heads/release-4.12" future-branch=release-4.12 org=openshift output="remote: This repository was archived so it is read-only.\nfatal: unable to access 'https://github.com/openshift/openshift-tests/': The requested URL returned error: 403\n" repo=openshift-tests source-file=openshift-openshift-tests-master.yaml variant=
> ```
> 
> The `error="<nil>"` at the end is due to the condition:
> 
> https://github.com/openshift/ci-tools/blob/68249882ebce83a5f9b093b313adad88d67f67dd/cmd/repo-brancher/main.go#L203
> 
> which I suppose is constructed that way to process as many repositories as possible before failing.

I think that one error which is not false positive. For other repos, e.g., `https://github.com/netobserv/network-observability-console-plugin`, the `release-4.13` branch is already in sync with `master` but we still see errors.
> https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-openshift-release-fast-forward/1578384477984395264

2022-11-22 09:09 UTC, closed without merging