Fix issue DPTP-3621 Add unmanaged flag to cluster-init
openshift/ci-tools pull request #3604
Opened 2023-09-06 17:40 UTC by bear-redhat

Add support for creating unmanaged clusters with `cluster-init`

2023-09-06 18:59 UTC, bear-redhat commented
/test e2e

2023-09-07 16:19 UTC, bear-redhat commented
/test e2e

2023-09-11 13:30 UTC, danilo-gemoli requested changes

2023-09-11 13:30 UTC, danilo-gemoli commented on cmd/cluster-init/update_bootstrap_secrets.go
> +	if o.clusterName != string(api.ClusterBuild01) && o.clusterName != string(api.ClusterBuild02) && !o.unmanaged {
Can you add a new unit test to cover this case?

2023-09-11 13:30 UTC, danilo-gemoli commented on cmd/cluster-init/update_secret_generator.go
> +	if !o.unmanaged {
Same here, can you add a new unit test to cover this case?

2023-09-12 13:02 UTC, bear-redhat commented
@danilo-gemoli  the comment is updated

2023-09-13 07:15 UTC, danilo-gemoli commented
/lgtm

2023-09-13 08:58 UTC, merged