[DPTP-3546] Verifying if issues are enable for automated branching
openshift/ci-tools pull request #4443
Opened 2024-12-09 18:47 UTC by hector-vido

Repos participating in [automated branching](https://docs.ci.openshift.org/docs/architecture/branching/#how-do-i-opt-my-repository-into-automated-branching) need to have github issues enabled to succeed. There is currently no precheck for this. It should be added as a check in check-gh-automation.

2024-12-10 03:17 UTC, hector-vido commented
/test all

2024-12-11 08:37 UTC, danilo-gemoli requested changes

2024-12-11 08:37 UTC, danilo-gemoli commented on cmd/check-gh-automation/main.go
> +			configData, found = configs.CiOperator[fmt.Sprintf("%s-%s-master.yaml", org, repo)]
I guess you could replace `fmt.Sprintf("%s-%s-master.yaml", org, repo)` with `(&api.Metadata{Org: org, Repo: repo, Branch: "master"}).Basename()`

2024-12-11 08:37 UTC, danilo-gemoli commented on cmd/check-gh-automation/main.go
> +				configData, found = configs.CiOperator[fmt.Sprintf("%s-%s-main.yaml", org, repo)]
Same as above ^

2024-12-11 08:37 UTC, danilo-gemoli commented on cmd/check-gh-automation/main.go
> +			if configData.Configuration.PromotionConfiguration != nil {
You can simplify and avoid the nil check here:
```golang
for _, target := range api.PromotionTargets(configData.Configuration.PromotionConfiguration) {
    if target.Namespace == "ocp" && !fullRepo.HasIssues {
        logger.Errorf("Repository %s/%s should have issues enable for automated branching.", org, repo)
        failing.Insert(orgRepo)
    }
}
```

2024-12-11 13:07 UTC, smg247 commented on cmd/check-gh-automation/main.go
> +	configs, _ := config.GetAllConfigs(o.releaseRepoPath)
We can't ignore the error here

2024-12-11 13:07 UTC, smg247 commented on cmd/check-gh-automation/main.go
> +			logger.Infof("No release repository path was given, ignoring automated branching verification.")
I think we should make this a `warn` level

2024-12-11 13:07 UTC, smg247 commented on hack/local-check-gh-automation.sh
> +fi
Can we accept this as a named parameter, rather than relying on positional args?

2024-12-11 13:08 UTC, smg247 commented on cmd/check-gh-automation/main.go
> +					if target.Namespace == "ocp" && !fullRepo.HasIssues {
I would create a constant for `"ocp"`

2024-12-11 17:03 UTC, smg247 commented on cmd/check-gh-automation/main.go
> +				configData, found = configs.CiOperator[(&api.Metadata{Org: org, Repo: repo, Branch: "master"}).Basename()]
You are searching "master" twice ;)

2024-12-11 17:21 UTC, smg247 commented
/lgtm

2024-12-12 00:41 UTC, merged